version: '3.8'

services:
  bot:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    volumes:
      - ./src:/app
      - ./logging.toml:/app/logging.toml
    command: python main.py
